name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15  # Общее ограничение времени
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      timeout-minutes: 5
      run: |
        choco install mingw -y --version 12.2.0 --no-progress
        choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System' --no-progress
        
        if (-not (Test-Path C:/SFML-2.5.1)) {
            Invoke-WebRequest -Uri "https://github.com/SFML/SFML/releases/download/2.5.1/SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit.zip" -OutFile "sfml.zip"
            Expand-Archive -Path sfml.zip -DestinationPath C:/
        }
        echo "C:\SFML-2.5.1\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Configure CMake
      run: |
        cmake -S . -B build -G "MinGW Makefiles" -DSFML_DIR="C:/SFML-2.5.1/lib/cmake/SFML"
        
    - name: Build
      run: |
        cmake --build build --config Release --parallel
        
    - name: Copy DLLs
      run: |
        Copy-Item "C:/SFML-2.5.1/bin/*.dll" -Destination "build/"
        $mingwPath = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
        if (Test-Path $mingwPath) {
            Copy-Item "$mingwPath\*.dll" -Destination "build/"
        }
        
    - name: Run executable
      timeout-minutes: 2
      run: |
        cd build
        .\arkanoid.exe || echo "::error::Application failed with exit code $LASTEXITCODE"
