name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        choco install mingw -y --version 8.1.0
        choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
        Invoke-WebRequest -Uri "https://github.com/SFML/SFML/releases/download/2.5.1/SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit.zip" -OutFile "sfml.zip"
        Expand-Archive -Path sfml.zip -DestinationPath C:/
        echo "C:\SFML-2.5.1\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Configure CMake
      run: |
        cmake -S . -B build -G "MinGW Makefiles" `
          -DSFML_DIR="C:/SFML-2.5.1/lib/cmake/SFML"
        
    - name: Build
      run: |
        cmake --build build --config Release -j 2
        
    - name: Copy DLLs
      run: |
        # Копируем все DLL из SFML и MinGW
        Copy-Item "C:/SFML-2.5.1/bin/*.dll" -Destination "build/"
        $MINGW_PATH = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
        Copy-Item "$MINGW_PATH\*.dll" -Destination "build/"
        
    - name: Verify dependencies
      run: |
        cd build
        $MINGW_PATH = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
        & "$MINGW_PATH\ldd.exe" arkanoid.exe
        
    - name: Run executable
      run: |
        # Запускаем без перенаправления, чтобы видеть вывод сразу
        if (Test-Path build/Release/arkanoid.exe) {
            cd build/Release
            .\arkanoid.exe
        } else {
            cd build
            .\arkanoid.exe
        }
