name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        choco install mingw -y --version 12.2.0
        choco install cmake.install -y --installargs 'ADD_CMAKE_TO_PATH=System'
        # Исправленная ссылка для SFML 2.5.0 (MinGW)
        Invoke-WebRequest -Uri "https://github.com/SFML/SFML/releases/download/2.5.0/SFML-2.5.0-windows-mingw-64-bit.zip" -OutFile "sfml.zip"
        Expand-Archive -Path sfml.zip -DestinationPath C:/
    
    - name: Configure CMake
      run: |
        cmake -S . -B build -G "MinGW Makefiles" -DSFML_DIR="C:/SFML-2.5.0/lib/cmake/SFML"
        
    - name: Build
      run: |
        cmake --build build --config Release
        
    - name: Copy DLLs
      run: |
        Copy-Item "C:/SFML-2.5.0/bin/*.dll" -Destination "build/"
        
    - name: Run executable
      run: |
        .\build\Release\arkanoid.exe
